@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Configuration {
  + Configuration(int): 
  + Configuration(): 
  # blocks: Piece[]
  + getBlocksType(int): int[]
  + getPositions(int): Tuple[]
   blocks: Piece[]
}
class Controller {
  + Controller(): 
  + initialize(): void
  ~ configurationClicked(ActionEvent): void
  - isNotOverlapping(Piece, double, double): boolean
  ~ reset(MouseEvent): void
}
class Main {
  + Main(): 
  + start(Stage): void
  + main(String[]): void
}
class Piece {
  + Piece(): 
  + Piece(int, String): 
  + toString(): String
   imageName: String
   type: int
   imageFill: String
}
class Tuple {
  + Tuple(int, int): 
  + y: int
  + x: int
   x: int
   y: int
}

Configuration  -[#595959,dashed]->  Configuration 
Configuration "1" *-[#595959,plain]-> "blocks\n*" Piece         
Configuration  -[#595959,dashed]->  Piece         : "«create»"
Configuration  -[#595959,dashed]->  Tuple         : "«create»"
Controller    "1" *-[#595959,plain]-> "_configuration\n1" Configuration 
Controller     -[#595959,dashed]->  Configuration : "«create»"
Controller     -[#595959,dashed]->  Controller    
Controller    "1" *-[#595959,plain]-> "selectedBlock\n1" Piece         
Main           -[#595959,dashed]->  Main          
Piece          -[#595959,dashed]->  Piece         
@enduml
