@startuml
!theme materia-outline

skinparam ArrowColor #00B4D8
skinparam ActorBorderColor #03045E
skinparam ActorFontColor #03045E
skinparam ActorBackgroundColor #CAF0F8
skinparam ParticipantFontColor #03045E
skinparam ParticipantBorderColor #03045E
skinparam ParticipantBackgroundColor #90E0EF
skinparam DatabaseBorderColor #03045E
skinparam DatabaseBackgroundColor #00B4D8
skinparam DatabaseFontColor #03045E
skinparam BackgroundColor #FFFFFF

actor Giocatore
participant Partita
database Log
participant NBM_Script

Giocatore -> Partita: esegui_NBM()

Partita -> NBM_Script: richiedi_NBM(configurazione_corrente)
NBM_Script -> NBM_Script: calcola_NBM()
NBM_Script --> Partita: restituisci(configurazione_NBM)

Partita -> Partita: aggiorna_configurazione_corrente(configurazione_NBM)\ncounter++
Partita -> Partita: aggiorna_storico_configurazioni(configurazione_corrente)
Partita -> Log: scrivi(storico_configurazioni)

Partita --> Giocatore: mostra(configurazione_corrente,\ncounter)

@enduml