@startuml

left to right direction

actor Giocatore
actor ExternalSystem

Giocatore --> (Scegliere configurazione iniziale)
Giocatore --> (Muovere i blocchi nelle posizioni consentite)
Giocatore --> (Utilizzare funzione di reset)
Giocatore --> (Utilizzare funzione di undo)
Giocatore --> (Richiedere «next best move»)
Giocatore --> (Visualizzare counter delle mosse effettuate)
Giocatore --> (Salvare lo stato corrente)
Giocatore --> (Ripristinare la partita salvata)

@enduml